language: c

os:
  - linux

compiler:
  - gcc
  - clang
  - cc

addons:
  apt:
    packages:
      - graphviz

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y xmlto

script: scripts/build.sh

# blacklist
branches:
  except:
    - gh-pages

# whitelist
branches:
  only:
    - master
    - devel
    - tests

notifications:
  recipients:
    - bert.timmerman@xs4all.nl
  email:
    on_success: change
    on_failure: always

